#!/bin/bash
#

if [ "$QUERY_STRING" = "" ] ; then
    QUERY_STRING="$1"
fi

url=`echo "$QUERY_STRING" | awk '{
	sub("Q=", "");
	gsub("!", "\\\\&");
	gsub("@", "?");
	print $1
}'`

echo $url >> log

case "$url" in
    http://archive.eso.org/dss/dss*)					;;
    http://www.cfa.harvard.edu/archive/dss*)				;;
    http://www.cfa.harvard.edu/catalog/scat*)				;;
    http://stdatu.stsci.edu/cgi-bin/dss_search*)			;;
    http://irsa.ipac.caltech.edu/cgi-bin/Oasis/2MASSImg/nph-2massimg*)	;;

    http://vizier.u-strasbg.fr/viz-bin/asu-tsv*)			;;

    *)	exit 1 ;;
esac

wget -O- -q --save-headers $url | (
 while read LINE; do
    case "$LINE" in
	""|"")
	    echo "Access-Control-Allow-Origin: *"
	    echo
	    cat
	    exit
	    ;;
	[Cc]ontent-[Ee]ncoding*)
	    case $LINE in
		*gzip*)
		    echo "Content-Encoding: gzip"
		    Encoding=1
		    ;;
	    esac
	    ;;
	[Cc]ontent-[Tt]ype*)
	    case $LINE in
		*gfits*)
		    if [ "$Encoding" = "" ] ; then 
			echo "Content-Encoding: gzip"
		    fi
		    ;;
	    esac
	    echo $LINE
	    ;;
    esac
 done
)
